apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9001
    env:
    - name: MINIO_ROOT_USER
      value: minioadmin
    - name: MINIO_ROOT_PASSWORD
      value: minioadmin
    - name: MINIO_BROWSER_LOGIN_ANIMATION
      value: 'off'      
    volumeMounts:
    - mountPath: /data
      name: localvolume
  volumes:
  - name: localvolume
    hostPath:
      path: /mnt/disk1/data
      type: DirectoryOrCreate
