---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vllm
  template:
    metadata:
      labels:
        app: app-vllm
    spec:
      containers:
        - name: app-vllm
          image: vllm/vllm-openai:latest
          env:
            - name: VLLM_ALLOW_RUNTIME_LORA_UPDATING
              value: "True"
          command: ["vllm"]
          args:
            - "serve"
            - "microsoft/Phi-3-mini-4k-instruct"
            - "--dtype"
            - "auto"
            - "--max-model-len"
            - "512"
            - "--enable-lora"
            - "--gpu-memory-utilization"
            - "0.8"
            - "--download-dir"
            - "/vllm-storage"
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: vllm-storage
              mountPath: /vllm-storage
      volumes:
        - name: vllm-storage
          persistentVolumeClaim:
            claimName: vllm-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app-vllm
  labels:
    app: app-vllm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: app-vllm