---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vllm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-vllm
  template:
    metadata:
      labels:
        app: app-vllm
    spec:
      containers:
        - name: app-vllm
          image: vllm/vllm-openai:latest
          env:
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: wandb
                key: WANDB_API_KEY
          resources:
            limits:
              nvidia.com/gpu: 1                
---
apiVersion: v1
kind: Service
metadata:
  name: app-vllm
  labels:
    app: app-vllm
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: app-vllm
