name: Module 2


on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    # paths:
    #   - 'module-2/**'

jobs:

  minio-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-python
        with:
          python-version: '3.10' 

      - name: Run minio
        run: |
          docker run -d -p 9000:9000 -p 9001:9001 quay.io/minio/minio server /data --console-address ":9001"

      - name: Setup env
        run: |
          pip install -r module-2/requirements.test.txt

      - name: Run test
        run: |
          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_ENDPOINT_URL=http://127.0.0.1:9000        
          aws s3api create-bucket --bucket test
          pytest -ss ./module-2/minio_storage/test_minio_client.py
