name: Module 5

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    # paths:
    #   - 'module-5/**'

jobs:

  docker-builds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push app-streamlit
        uses: docker/build-push-action@v6
        with:
          context: module-5/
          push: true
          target: app-streamlit
          tags: ghcr.io/kyryl-opens-ml/app-streamlit:latest

      - name: Build and push app-fastapi
        uses: docker/build-push-action@v6
        with:
          context: module-5/
          push: true
          target: app-fastapi
          tags: ghcr.io/kyryl-opens-ml/app-fastapi:latest

      - name: Build and push app-pytriton
        uses: docker/build-push-action@v6
        with:
          context: module-5/
          push: true
          target: app-pytriton
          tags: ghcr.io/kyryl-opens-ml/app-pytriton:latest

      - name: Build and push app-kserve
        uses: docker/build-push-action@v6
        with:
          context: module-5/
          push: true
          target: app-kserve
          tags: ghcr.io/kyryl-opens-ml/app-kserve:latest          