name: Module 2


on:
  workflow_dispatch:
  # push:
  pull_request:
    branches:
      - main


jobs:

  minio-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Run minio
        run: |
          docker run -d -p 9000:9000 -p 9001:9001 quay.io/minio/minio server /data --console-address ":9001"

        
      - name: Setup env
        run: |
          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_ENDPOINT_URL=http://127.0.0.1:9000
          pip install -r module-2/requirements.txt

      - name: Run test
        run: |
          pytest -ss ./module-2/minio_storage/test_minio_client.py